openapi: 3.0.0
info:
  title: Fitness Program API
  version: 1.0.0
servers:
  - url: https://us-west-2.aws.data.mongodb-api.com/app/data-dfkis/endpoint
paths:
  /CreateProgram:
    post:
      summary: Add a new fitness program
      operationId: createProgram
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Program'
      responses:
        '201':
          description: Fitness program created
        '400':
          description: Invalid input
  
  /CreateWorkout:
    post:
      summary: Create a new workout session
      operationId: createWorkout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workout' # Reference to the Workout schema
      responses:
        '201':
          description: Workout session created
        '400':
          description: Invalid input

  /GetRecentWorkouts:
    get:
      summary: Get recent workout sessions
      operationId: getRecentWorkouts
      responses:
        '200':
          description: List of recent workout sessions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout' # Reference to the Workout schema

components:
  schemas:
    
    Program:
      type: object
      required:
        - programName
        - description
        - goal
        - durationWeeks
        - daysPerWeek
        - phases
      properties:
        programName:
          type: string
        description:
          type: string
        goal:
          type: string
        durationWeeks:
          type: string
        daysPerWeek:
          type: integer
        level:
          type: string
        phases:
          type: array
          items:
            $ref: '#/components/schemas/Phase'
    
    Phase:
      type: object
      required:
        - phaseName
        - progressionRules
        - phaseSequence
        - durationWeeks
        - weeklyStructure
      properties:
        phaseName:
          type: string
        progressionRules:
          type: string
        phaseSequence:
          type: integer
        durationWeeks:
          type: string
        weeklyStructure:
          $ref: '#/components/schemas/WeeklyStructure'
    
    WeeklyStructure:
      type: object
      required:
        - days
      properties:
        days:
          type: array
          items:
            $ref: '#/components/schemas/Day'
    
    Day:
      type: object
      required:
        - day
        - exercises
      properties:
        day:
          type: string
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/Exercise'
    
    Exercise:
      type: object
      required:
        - name
        - sets
        - reps
        - intensity
      properties:
        name:
          type: string
        sets:
          type: string
        reps:
          type: string
        intensity:
          type: string
        weight:
          type: number # Optional weight field. Used primarily for recording workout sessions.
        exerciseNotes:
          type: string # Optional notes field. Used primarily for recording workout sessions.

    RecentWorkouts:
      type: object
      properties:
        workoutSessions:
          type: array
          items:
            $ref: '#/components/schemas/Workout'

    Workout:
      type: object
      required:
        - programId
        - workoutSequenceCode
        - exercises
      properties:
        programId:
          type: string
        workoutNotes:
          type: string
        workoutSequenceCode:
          type: string
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/Exercise'
